Repository ARM-software/CMSIS_5, pull requests merged in 2019-06, with the labels that each got.

#599 Fix out_shift value of 31
  CMSIS/NN/Include/arm_nnsupportfunctions.h
Labels: NN, review

#512 Fix issue #511.
  CMSIS/NN/Source/PoolingFunctions/arm_pool_q7_HWC.c
Labels: NN, enhancement, review

#601 Include paths for transform tests in ArmDS A5 project
  CMSIS/DSP/DSP_Lib_TestSuite/DspLibTest_FVP_A5/.cproject
  CMSIS/DSP/DSP_Lib_TestSuite/DspLibTest_FVP_A5/.settings/language.settings.xml
  CMSIS/DSP/DSP_Lib_TestSuite/DspLibTest_FVP_A5/DspLibTest_FVP_A5.launch
Labels: DSP, review

#607 `arm_nn_tables.h`: removed duplicated declaration
  CMSIS/NN/Include/arm_nn_tables.h
Labels: NN, review

#608 Saturating doubling high multiply & divide by power of two
  CMSIS/NN/Include/arm_nnsupportfunctions.h
Labels: NN, review

#612 Depthwise convoltution with asymmetric quantization support.
  CMSIS/NN/Include/arm_nnfunctions.h
  CMSIS/NN/Include/arm_nnsupportfunctions.h
  CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_u8_basic_ver1.c
Labels: NN, review

#614 Update of revision history for CMSIS-NN
  ARM.CMSIS.pdsc
  CMSIS/DoxyGen/General/src/introduction.txt
  CMSIS/DoxyGen/NN/nn.dxy
  CMSIS/DoxyGen/NN/src/history.txt
Labels: NN
