Repository ARM-software/CMSIS_5, pull requests merged in 2019-10, with the labels that each got.

#699 CMSIS-NN: Fix output scaling in elementwise_add
  CMSIS/NN/Source/BasicMathFunctions/arm_elementwise_add_s8.c
Labels: NN, review

#698 CMSIS-NN: Implement bit-accurate S8 Softmax (non-DSP)
  CMSIS/DSP/Include/arm_math.h
  CMSIS/NN/Include/arm_nnfunctions.h
  CMSIS/NN/Include/arm_nnsupportfunctions.h
  CMSIS/NN/Source/ReshapeFunctions/arm_reshape_s8.c
  CMSIS/NN/Source/SoftmaxFunctions/arm_softmax_s8.c
Labels: NN, review

#691 Change OS_THREAD_LIBSPACE_NUM to be defined as a (compiler) macro
  ARM.CMSIS.pdsc
  CMSIS/RTOS2/RTX/Config/RTX_Config.h
Labels: RTOS, review

#711 CMSIS_NN: Update 1x1 conv for s8
  CMSIS/NN/Include/arm_nnfunctions.h
  CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_1x1_s8_fast.c
  CMSIS/NN/Source/ConvolutionFunctions/arm_nn_mat_mult_kernel_s8_s16_reordered.c
Labels: NN, review

#713 Added arm_abs_q31.c Neon
  CMSIS/DSP/Source/BasicMathFunctions/arm_abs_q31.c
Labels: DSP, review

#717 CMSIS-NN: MVE support for s8 Fully connected and MatMul
  CMSIS/NN/Include/arm_nnfunctions.h
  CMSIS/NN/Source/FullyConnectedFunctions/arm_fully_connected_s8.c
Labels: NN, review
