Repository ARM-software/CMSIS_5, pull requests merged in 2020-06, with the labels that each got.

#939 Fix - arm_math.h: Use the float suffix in arm_clarke_f32
  CMSIS/DSP/Include/arm_math.h
Labels: DSP, review

#935 CMSIS-NN: Fix warnings
  CMSIS/DSP/Source/BasicMathFunctions/arm_add_q7.c
  CMSIS/NN/Include/arm_nnfunctions.h
  CMSIS/NN/Source/ActivationFunctions/arm_relu_q7.c
  CMSIS/NN/Source/BasicMathFunctions/arm_elementwise_mul_s8.c
  CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_1_x_n_s8.c
  CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_1x1_s8_fast.c
  CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_s8.c
  CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_3x3_s8.c
  CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_s8_opt.c
  CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_u8_basic_ver1.c
  CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_wrapper_s8.c
  CMSIS/NN/Source/ConvolutionFunctions/arm_nn_depthwise_conv_s8_core.c
  CMSIS/NN/Source/ConvolutionFunctions/arm_nn_mat_mult_kernel_s8_s16.c
  CMSIS/NN/Source/ConvolutionFunctions/arm_nn_mat_mult_s8.c
  CMSIS/NN/Source/FullyConnectedFunctions/arm_fully_connected_s8.c
  CMSIS/NN/Source/NNSupportFunctions/arm_nn_accumulate_q7_to_q15.c
  CMSIS/NN/Source/NNSupportFunctions/arm_nn_add_q7.c
  CMSIS/NN/Source/NNSupportFunctions/arm_q7_to_q15_no_shift.c
  CMSIS/NN/Source/NNSupportFunctions/arm_q7_to_q15_reordered_no_shift.c
  CMSIS/NN/Source/NNSupportFunctions/arm_q7_to_q15_reordered_with_offset.c
  CMSIS/NN/Source/PoolingFunctions/arm_avgpool_s8.c
  CMSIS/NN/Source/SoftmaxFunctions/arm_softmax_u8.c
Labels: NN

#942 CMSIS-NN: Use int for loop variables
  CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q15_basic.c
  CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q15_fast.c
  CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q15_fast_nonsquare.c
  CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_RGB.c
  CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_basic.c
  CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_basic_nonsquare.c
  CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_fast.c
Labels: NN

#950 CMSIS-NN: Add unit test support for fully_connected
  CMSIS/NN/Tests/UnitTest/PregeneratedData/fully_connected/bias.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/fully_connected/input.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/fully_connected/kernel.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/fully_connected/params.txt
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/fully_connected/biases_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/fully_connected/config_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/fully_connected/input_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/fully_connected/output_ref_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/fully_connected/test_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/fully_connected/weights_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/test_arm_fully_connected_s8/Unity/unity_test_arm_fully_connected_s8.c
  CMSIS/NN/Tests/UnitTest/TestCases/test_arm_fully_connected_s8/test_arm_fully_connected_s8.c
  CMSIS/NN/Tests/UnitTest/generate_test_data.py
  CMSIS/NN/Tests/UnitTest/unittest_targets.py
Labels: NN, review
