Repository ARM-software/CMSIS_5, pull requests merged in 2020-03, with the labels that each got.

#776 Device: SC300: Fix wrong SC300 core header file inclusion
  ARM.CMSIS.pdsc
  Device/ARM/ARMSC000/Include/ARMSC000.h
  Device/ARM/ARMSC300/Include/ARMSC300.h
Labels: CORE, bug

#842 CMSIS-NN: Improve performance of convolution for MVE
  CMSIS/NN/Include/arm_nnsupportfunctions.h
  CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_s8.c
  CMSIS/NN/Source/ConvolutionFunctions/arm_nn_mat_mult_s8.c
Labels: NN, review

#843 CMSIS-NN: Add information on legacy and TFL micro compliant APIs
  CMSIS/NN/README.md
Labels: NN, review

#848 CMSIS-NN: Use __RESTRICT instead of restrict keyword
  CMSIS/NN/Include/arm_nnsupportfunctions.h
Labels: NN, review

#841 CMSIS-NN: Add unit test
  CMSIS/NN/.gitignore
  CMSIS/NN/Tests/UnitTest/PregeneratedData/basic/bias.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/basic/input.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/basic/kernel.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/basic/params.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/kernel1x1/bias.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/kernel1x1/input.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/kernel1x1/kernel.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/kernel1x1/params.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/stride2pad1/bias.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/stride2pad1/input.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/stride2pad1/kernel.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/stride2pad1/params.txt
  CMSIS/NN/Tests/UnitTest/Profiles/mbed_app.json
  CMSIS/NN/Tests/UnitTest/Profiles/release.json
  CMSIS/NN/Tests/UnitTest/README.md
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/basic/biases_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/basic/config_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/basic/input_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/basic/output_mult_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/basic/output_ref_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/basic/output_shift_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/basic/test_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/basic/weights_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/kernel1x1/biases_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/kernel1x1/config_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/kernel1x1/input_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/kernel1x1/output_mult_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/kernel1x1/output_ref_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/kernel1x1/output_shift_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/kernel1x1/test_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/kernel1x1/weights_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/stride2pad1/biases_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/stride2pad1/config_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/stride2pad1/input_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/stride2pad1/output_mult_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/stride2pad1/output_ref_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/stride2pad1/output_shift_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/stride2pad1/test_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/stride2pad1/weights_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/Utils/validate.h
  CMSIS/NN/Tests/UnitTest/TestCases/test_arm_convolve_1x1_s8_fast/Unity/unity_test_arm_convolve_1x1_s8_fast.c
  CMSIS/NN/Tests/UnitTest/TestCases/test_arm_convolve_1x1_s8_fast/test_arm_convolve_1x1_s8_fast.c
  CMSIS/NN/Tests/UnitTest/TestCases/test_arm_convolve_s8/Unity/unity_test_arm_convolve_s8.c
  CMSIS/NN/Tests/UnitTest/TestCases/test_arm_convolve_s8/test_arm_convolve_s8.c
  CMSIS/NN/Tests/UnitTest/TestCases/test_arm_depthwise_conv_s8/TestRunner/test_arm_depthwise_conv_s8_runner.c
  CMSIS/NN/Tests/UnitTest/TestCases/test_arm_depthwise_conv_s8/Unity/unity_test_arm_depthwwise_conv_s8.c
  CMSIS/NN/Tests/UnitTest/TestCases/test_arm_depthwise_conv_s8/test_arm_depthwise_conv_s8.c
  CMSIS/NN/Tests/UnitTest/TestCases/test_arm_depthwise_conv_s8_opt/TestRunner/test_arm_depthwise_conv_s8_opt_runner.c
  CMSIS/NN/Tests/UnitTest/TestCases/test_arm_depthwise_conv_s8_opt/Unity/unity_test_arm_depthwise_conv_s8_opt.c
  CMSIS/NN/Tests/UnitTest/TestCases/test_arm_depthwise_conv_s8_opt/test_arm_depthwise_conv_s8_opt.c
  CMSIS/NN/Tests/UnitTest/generate_test_data.py
  CMSIS/NN/Tests/UnitTest/requirements.txt
  CMSIS/NN/Tests/UnitTest/unittest_targets.py
Labels: NN, review

#847 CMSIS-NN: Use SXTAB instead of SXTB and SADD16 for DSP extension
  CMSIS/NN/Source/NNSupportFunctions/arm_q7_to_q15_reordered_with_offset.c
  CMSIS/NN/Source/NNSupportFunctions/arm_q7_to_q15_with_offset.c
Labels: NN, review

#851 CMSIS_NN: Remove DSP extension optimization for avg pool
  CMSIS/NN/Include/arm_nnfunctions.h
  CMSIS/NN/README.md
  CMSIS/NN/Source/PoolingFunctions/arm_avgpool_s8.c
Labels: NN, review

#850 CMSIS-NN: Warning fixes in depthwise conv(MVE)
  CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_s8.c
  CMSIS/NN/Source/ConvolutionFunctions/arm_nn_depthwise_conv_s8_core.c
Labels: NN, review

#853 CMSIS-NN: revert intrinsics for vdup(MVE)
  CMSIS/NN/Source/ConvolutionFunctions/arm_nn_mat_mult_s8.c
Labels: NN, review

#855 CMSIS-NN: Revert *_x/1_* intrinsics for MVE
  CMSIS/NN/Include/arm_nnsupportfunctions.h
  CMSIS/NN/Source/ConvolutionFunctions/arm_nn_mat_mult_s8.c
Labels: NN, review

#859 CMSIS-NN: Add missing API to interface
  CMSIS/NN/Include/arm_nnfunctions.h
Labels: NN, bug, review

#857 CMSIS-NN: Add full code coverage for test_arm_convolve_1x1_fast
  CMSIS/NN/Tests/UnitTest/PregeneratedData/kernel1x1/bias.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/kernel1x1/input.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/kernel1x1/kernel.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/kernel1x1/params.txt
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/kernel1x1/biases_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/kernel1x1/config_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/kernel1x1/input_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/kernel1x1/output_mult_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/kernel1x1/output_ref_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/kernel1x1/output_shift_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/kernel1x1/test_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/kernel1x1/weights_data.h
  CMSIS/NN/Tests/UnitTest/generate_test_data.py
Labels: NN, review

#862 CMSIS-NN: Improve performance of depthwise conv for MVE
  CMSIS/DoxyGen/NN/src/history.txt
  CMSIS/NN/Include/arm_nnfunctions.h
  CMSIS/NN/Include/arm_nnsupportfunctions.h
  CMSIS/NN/README.md
  CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_s8_opt.c
  CMSIS/NN/Source/NNSupportFunctions/arm_nn_depthwise_conv_nt_t_padded_s8.c
  CMSIS/NN/Source/NNSupportFunctions/arm_nn_depthwise_conv_nt_t_s8.c
Labels: NN, review

#835 core: add SPDX identifier
  CMSIS/Core/Include/cmsis_iccarm.h
  CMSIS/Core_A/Include/cmsis_iccarm.h
Labels: CORE, review

#863 CMSIS-NN List source files and update revision number
  ARM.CMSIS.pdsc
  CMSIS/DoxyGen/NN/src/history.txt
Labels: NN, review

#864 CMSIS-NN Doxygen formatting fixes
  CMSIS/NN/Include/arm_nnsupportfunctions.h
  CMSIS/NN/Source/NNSupportFunctions/arm_nn_depthwise_conv_nt_t_padded_s8.c
  CMSIS/NN/Source/NNSupportFunctions/arm_nn_depthwise_conv_nt_t_s8.c
  CMSIS/NN/Source/NNSupportFunctions/arm_nn_mat_mult_nt_t_s8.c
  CMSIS/NN/Source/NNSupportFunctions/arm_nn_vec_mat_mult_t_s8.c
Labels: NN, review

#865 Updated pmu_armv8.h with PMU functions and macro definitions.
  CMSIS/Core/Include/core_armv81mml.h
  CMSIS/Core/Include/core_cm55.h
  CMSIS/Core/Include/pmu_armv8.h
Labels: CORE, review

#869 CMSIS-NN Add MVE support in requantization for a variant of DWC
  ARM.CMSIS.pdsc
  CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_s8.c
Labels: NN, review

#871 Updated last four PMU functions to return void
  CMSIS/Core/Include/pmu_armv8.h
Labels: CORE, enhancement

#868 RTOS2: Added Blinky and MsgQueue examples for IAR
  ARM.CMSIS.pdsc
  CMSIS/RTOS2/RTX/Examples_IAR/Blinky/Abstract.txt
  CMSIS/RTOS2/RTX/Examples_IAR/Blinky/Blinky.c
  CMSIS/RTOS2/RTX/Examples_IAR/Blinky/Blinky/Blinky.ewd
  CMSIS/RTOS2/RTX/Examples_IAR/Blinky/Blinky/Blinky.ewp
  CMSIS/RTOS2/RTX/Examples_IAR/Blinky/Blinky/settings/Blinky.crun
  CMSIS/RTOS2/RTX/Examples_IAR/Blinky/Blinky/settings/Blinky.dbgdt
  CMSIS/RTOS2/RTX/Examples_IAR/Blinky/Blinky/settings/Blinky.dnx
  CMSIS/RTOS2/RTX/Examples_IAR/MsgQueue/Abstract.txt
  CMSIS/RTOS2/RTX/Examples_IAR/MsgQueue/MsgQueue/MsgQueue.ewd
  CMSIS/RTOS2/RTX/Examples_IAR/MsgQueue/MsgQueue/MsgQueue.ewp
  CMSIS/RTOS2/RTX/Examples_IAR/MsgQueue/MsgQueue/settings/MsgQueue.crun
  CMSIS/RTOS2/RTX/Examples_IAR/MsgQueue/MsgQueue/settings/MsgQueue.dbgdt
  CMSIS/RTOS2/RTX/Examples_IAR/MsgQueue/MsgQueue/settings/MsgQueue.dnx
  CMSIS/RTOS2/RTX/Examples_IAR/MsgQueue/main.c
Labels: RTOS, review
