Repository ARM-software/CMSIS_5, pull requests merged in 2020-04, with the labels that each got.

#877 CMSIS-NN Improve performance of softmax for MVE
  CMSIS/NN/Source/SoftmaxFunctions/arm_softmax_s8.c
  CMSIS/NN/Source/SoftmaxFunctions/arm_softmax_u8.c
Labels: NN, review

#880 CMSIS-NN: Fix for batch greater than 1 case in Fully Connected
  CMSIS/NN/Source/FullyConnectedFunctions/arm_fully_connected_s8.c
Labels: NN, bug, review

#881 Update CMSIS-NN documentation
  CMSIS/NN/Include/arm_nnfunctions.h
Labels: NN, review

#885 CMSIS-NN: Fix incorrect data type in Softmax (Interface change)
  CMSIS/NN/Include/arm_nnfunctions.h
  CMSIS/NN/Source/SoftmaxFunctions/arm_softmax_s8.c
Labels: NN, bug, review

#509 Fix bug #470 (Bug related to arm_nn_activations_direct_q15)
  CMSIS/NN/Source/ActivationFunctions/arm_nn_activations_q15.c
Labels: NN, bug, review

#883 CMSIS-NN: Tail Predicate Loops in Fully Connected operator
  CMSIS/NN/Source/FullyConnectedFunctions/arm_fully_connected_s8.c
  CMSIS/NN/Source/NNSupportFunctions/arm_nn_vec_mat_mult_t_s8.c
Labels: NN, review

#894 Macro fixes, New macro definitions, ARM_PMU_Get_EVCNTR() update
  CMSIS/Core/Include/core_armv81mml.h
  CMSIS/Core/Include/core_cm55.h
  CMSIS/Core/Include/pmu_armv8.h
Labels: CORE, bug

#904 CMSIS-NN: CMSIS-NN structs for the TensorFlowLite micro compliant functions
  CMSIS/NN/Include/arm_nn_types.h
Labels: NN, review
