Repository ARM-software/CMSIS_5, pull requests merged in 2020-02, with the labels that each got.

#819 CMSIS-DSP: Improved arm_quick_sort_f32
  CMSIS/DSP/Source/SupportFunctions/arm_quick_sort_f32.c
  CMSIS/DSP/Testing/desc.txt
Labels: DSP, review

#817 CMSIS-NN: Fix compiler warnings
  CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_1x1_HWC_q7_fast_nonsquare.c
  CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q15_basic.c
  CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q15_fast.c
  CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q15_fast_nonsquare.c
  CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_RGB.c
  CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_basic.c
  CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_basic_nonsquare.c
  CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_fast.c
  CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_fast_nonsquare.c
  CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_s8.c
  CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_separable_conv_HWC_q7.c
  CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_separable_conv_HWC_q7_nonsquare.c
  CMSIS/NN/Source/ConvolutionFunctions/arm_nn_mat_mult_kernel_q7_q15.c
  CMSIS/NN/Source/ConvolutionFunctions/arm_nn_mat_mult_kernel_q7_q15_reordered.c
  CMSIS/NN/Source/FullyConnectedFunctions/arm_fully_connected_mat_q7_vec_q15.c
  CMSIS/NN/Source/FullyConnectedFunctions/arm_fully_connected_mat_q7_vec_q15_opt.c
  CMSIS/NN/Source/FullyConnectedFunctions/arm_fully_connected_q15.c
  CMSIS/NN/Source/FullyConnectedFunctions/arm_fully_connected_q15_opt.c
  CMSIS/NN/Source/FullyConnectedFunctions/arm_fully_connected_q7.c
  CMSIS/NN/Source/FullyConnectedFunctions/arm_fully_connected_q7_opt.c
  CMSIS/NN/Source/FullyConnectedFunctions/arm_fully_connected_s8.c
  CMSIS/NN/Source/NNSupportFunctions/arm_nn_mult_q15.c
  CMSIS/NN/Source/NNSupportFunctions/arm_q7_to_q15_with_offset.c
  CMSIS/NN/Source/PoolingFunctions/arm_pool_q7_HWC.c
Labels: NN, review

#821 CMSIS-NN: Update API comment for arm_convolve_1_x_n_s8
  CMSIS/NN/Include/arm_nnfunctions.h
Labels: NN, review

#830 CMSIS-NN: Update comment on input offset
  CMSIS/NN/Include/arm_nnfunctions.h
Labels: NN, review

#822 CMSIS-NN: Optimized fully connected layer for Cortex-M4/M7
  CMSIS/NN/Include/arm_nnsupportfunctions.h
  CMSIS/NN/Source/FullyConnectedFunctions/arm_fully_connected_s8.c
  CMSIS/NN/Source/NNSupportFunctions/arm_nn_vec_mat_mult_t_s8.c
Labels: NN, review

#834 Update ARMv81MML_DSP_DP_MVE_FP.h
  Device/ARM/ARMv81MML/Include/ARMv81MML_DSP_DP_MVE_FP.h
Labels: CORE, review

#826 CMSIS-NN: Optimized matrix multiplication function for Cortex-M7
  CMSIS/DoxyGen/NN/src/history.txt
  CMSIS/NN/Include/arm_nnfunctions.h
  CMSIS/NN/Include/arm_nnsupportfunctions.h
  CMSIS/NN/README.md
  CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_1x1_s8_fast.c
  CMSIS/NN/Source/NNSupportFunctions/arm_nn_mat_mult_nt_t_s8.c
Labels: NN, review

#825 CMSIS-NN Opt: Optimize Depthwise convolution 3x3 w/ unit multiplier o…
  CMSIS/DoxyGen/NN/src/history.txt
  CMSIS/NN/Include/arm_nnfunctions.h
  CMSIS/NN/README.md
  CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_3x3_s8.c
Labels: NN, review

#836 CMSIS-NN/DSP: Remove ARM_MATH_LOOPUNROLL
  CMSIS/NN/Include/arm_nnfunctions.h
  CMSIS/NN/Source/ActivationFunctions/arm_relu_q15.c
  CMSIS/NN/Source/ActivationFunctions/arm_relu_q7.c
  CMSIS/NN/Source/BasicMathFunctions/arm_elementwise_add_s8.c
  CMSIS/NN/Source/BasicMathFunctions/arm_elementwise_mul_s8.c
  CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_1_x_n_s8.c
  CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_s8.c
  CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_s8_opt.c
  CMSIS/NN/Source/ConvolutionFunctions/arm_nn_mat_mult_kernel_s8_s16.c
  CMSIS/NN/Source/ConvolutionFunctions/arm_nn_mat_mult_kernel_s8_s16_reordered.c
  CMSIS/NN/Source/NNSupportFunctions/arm_q7_to_q15_no_shift.c
  CMSIS/NN/Source/NNSupportFunctions/arm_q7_to_q15_reordered_with_offset.c
  CMSIS/NN/Source/NNSupportFunctions/arm_q7_to_q15_with_offset.c
  CMSIS/NN/Source/PoolingFunctions/arm_avgpool_s8.c
  CMSIS/NN/Source/PoolingFunctions/arm_max_pool_s8_opt.c
  CMSIS/NN/Source/SoftmaxFunctions/arm_softmax_q7.c
Labels: NN, review
