Repository ARM-software/CMSIS_5, pull requests merged in 2020-12, with the labels that each got.

#1062 CMSIS-NN: Fix fully connected unit test
  CMSIS/NN/Tests/UnitTest/generate_test_data.py
Labels: NN, bug

#1065 CMSIS-NN: Add .clang-format file
  CMSIS/NN/.clang-format
Labels: NN, enhancement, review

#1067 CMSIS-NN: Improve MVE performance of FC operator
  CMSIS/NN/Source/NNSupportFunctions/arm_nn_vec_mat_mult_t_s8.c
Labels: NN, review

#1069 CMSIS-NN: Add new test cases for Fully Connected
  CMSIS/NN/Tests/UnitTest/PregeneratedData/fully_connected_mve_0/bias.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/fully_connected_mve_0/input.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/fully_connected_mve_0/kernel.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/fully_connected_mve_0/params.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/fully_connected_mve_1/bias.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/fully_connected_mve_1/input.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/fully_connected_mve_1/kernel.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/fully_connected_mve_1/params.txt
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/fully_connected_mve_0/biases_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/fully_connected_mve_0/config_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/fully_connected_mve_0/input_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/fully_connected_mve_0/output_ref_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/fully_connected_mve_0/test_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/fully_connected_mve_0/weights_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/fully_connected_mve_1/biases_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/fully_connected_mve_1/config_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/fully_connected_mve_1/input_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/fully_connected_mve_1/output_ref_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/fully_connected_mve_1/test_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/fully_connected_mve_1/weights_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/test_arm_fully_connected_s8/Unity/unity_test_arm_fully_connected_s8.c
  CMSIS/NN/Tests/UnitTest/TestCases/test_arm_fully_connected_s8/test_arm_fully_connected_s8.c
  CMSIS/NN/Tests/UnitTest/generate_test_data.py
Labels: NN, review

#1071 CMSIS-DSP: Fix signed/unsigned integer data type issue
  CMSIS/DSP/Source/BasicMathFunctions/arm_and_u16.c
  CMSIS/DSP/Source/BasicMathFunctions/arm_and_u32.c
  CMSIS/DSP/Source/BasicMathFunctions/arm_and_u8.c
  CMSIS/DSP/Source/BasicMathFunctions/arm_not_u16.c
  CMSIS/DSP/Source/BasicMathFunctions/arm_not_u32.c
  CMSIS/DSP/Source/BasicMathFunctions/arm_not_u8.c
  CMSIS/DSP/Source/BasicMathFunctions/arm_or_u16.c
  CMSIS/DSP/Source/BasicMathFunctions/arm_or_u32.c
  CMSIS/DSP/Source/BasicMathFunctions/arm_or_u8.c
  CMSIS/DSP/Source/BasicMathFunctions/arm_xor_u16.c
  CMSIS/DSP/Source/BasicMathFunctions/arm_xor_u32.c
  CMSIS/DSP/Source/BasicMathFunctions/arm_xor_u8.c
Labels: DSP, review
