Repository ARM-software/CMSIS_5, pull requests merged in 2020-01, with the labels that each got.

#781 added missing pad_x argument for arm_max_pool_s8
  CMSIS/NN/Source/PoolingFunctions/arm_max_pool_s8_opt.c
Labels: NN, review

#782 fixed unused variable error for arm_convolve_s8_1x1_fast
  CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_1x1_s8_fast.c
Labels: NN, review

#780 Removed unnecessary casts
  CMSIS/NN/Source/FullyConnectedFunctions/arm_fully_connected_q7.c
Labels: NN, review

#799 CMSIS-NN: Improve performance of 1x1 conv for MVE
  CMSIS/DoxyGen/NN/src/history.txt
  CMSIS/NN/Include/arm_nnsupportfunctions.h
  CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_1x1_s8_fast.c
  CMSIS/NN/Source/NNSupportFunctions/arm_nn_mat_mul_core_1x_s8.c
  CMSIS/NN/Source/NNSupportFunctions/arm_nn_mat_mul_core_4x_s8.c
Labels: NN, review

#801 CMSIS-NN: remove output channel constraint on 1x1 conv
  CMSIS/NN/Include/arm_nnfunctions.h
  CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_1x1_s8_fast.c
  CMSIS/NN/Source/ConvolutionFunctions/arm_nn_mat_mult_kernel_s8_s16_reordered.c
Labels: NN, review

#808 CMSIS-NN: 1xN conv support for MVE
  CMSIS/DoxyGen/NN/src/history.txt
  CMSIS/NN/Include/arm_nnfunctions.h
  CMSIS/NN/Include/arm_nnsupportfunctions.h
  CMSIS/NN/README.md
  CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_1_x_n_s8.c
  CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_1x1_s8_fast.c
  CMSIS/NN/Source/NNSupportFunctions/arm_nn_mat_mul_core_1x_s8.c
  CMSIS/NN/Source/NNSupportFunctions/arm_nn_mat_mul_core_4x_s8.c
Labels: NN, review

#811 CMSIS-NN: Fix incorrect index usage in conv for MVE
  CMSIS/NN/Source/ConvolutionFunctions/arm_nn_mat_mult_kernel_s8_s16.c
Labels: NN, bug, review

#796 CMSIS CORE: Add support for __SXTB16_RORn
  CMSIS/Core/Include/cmsis_armcc.h
  CMSIS/Core/Include/cmsis_armclang.h
  CMSIS/Core/Include/cmsis_armclang_ltm.h
  CMSIS/Core/Include/cmsis_gcc.h
  CMSIS/Core/Include/cmsis_iccarm.h
  CMSIS/CoreValidation/Source/CV_CoreSimd.c
  CMSIS/DoxyGen/Core/src/Ref_cm4_simd.txt
Labels: CORE, enhancement
