Repository ARM-software/CMSIS_5, pull requests merged in 2020-05, with the labels that each got.

#909 CMSIS-NN: Fix batch dimension in arm_convolve_s8
  CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_s8.c
Labels: NN, review

#908 CMSIS-NN: Use arithmetic shifting in arm_nn_mult
  CMSIS/NN/Source/NNSupportFunctions/arm_nn_mult_q15.c
  CMSIS/NN/Source/NNSupportFunctions/arm_nn_mult_q7.c
Labels: NN, review

#913 CMSIS-NN: Fix and improve performance of depthwise conv u8
  CMSIS/NN/Include/arm_nnfunctions.h
  CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_u8_basic_ver1.c
Labels: NN, bug, review

#918 CMSIS-NN: Fix warning in arm_nnsupportfunctions.h
  CMSIS/NN/Include/arm_nnsupportfunctions.h
Labels: NN, review

#923 CMSIS-NN: Adopted the new API interface in convolution functions
  CMSIS/NN/Include/arm_nnfunctions.h
  CMSIS/NN/README.md
  CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_1_x_n_s8.c
  CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_1x1_s8_fast.c
  CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_s8.c
  CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_wrapper_s8.c
Labels: NN, review

#924 CMSIS-NN: Update unit test for convolution as per new interface
  CMSIS/NN/Tests/UnitTest/TestCases/test_arm_convolve_1x1_s8_fast/test_arm_convolve_1x1_s8_fast.c
  CMSIS/NN/Tests/UnitTest/TestCases/test_arm_convolve_s8/Unity/unity_test_arm_convolve_s8.c
  CMSIS/NN/Tests/UnitTest/TestCases/test_arm_convolve_s8/test_arm_convolve_s8.c
Labels: NN, review

#928 fixed typo in MPU->RASR register name
  CMSIS/Core/Include/mpu_armv7.h
  CMSIS/DoxyGen/Core/src/RegMap_CMSIS2ARM_Doc.txt
Labels: CORE, bug

#930 CMSIS-NN: Update DW conv to new interface
  CMSIS/DoxyGen/NN/src/history.txt
  CMSIS/NN/Include/arm_nn_types.h
  CMSIS/NN/Include/arm_nnfunctions.h
  CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_3x3_s8.c
  CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_s8.c
  CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_s8_opt.c
  CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_wrapper_s8.c
Labels: NN, review

#931 CMSIS-NN: Update average pool and fully conncted to new interface
  CMSIS/NN/Include/arm_nn_types.h
  CMSIS/NN/Include/arm_nnfunctions.h
  CMSIS/NN/Source/FullyConnectedFunctions/arm_fully_connected_s8.c
  CMSIS/NN/Source/PoolingFunctions/arm_avgpool_s8.c
Labels: NN, review

#932 CMSIS-NN: Update average pool tc to new interface
  CMSIS/NN/Tests/UnitTest/PregeneratedData/avgpooling_1/input.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/avgpooling_1/params.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/avgpooling_2/input.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/avgpooling_2/params.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/avgpooling_3/input.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/avgpooling_3/params.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/avgpooling_4/input.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/avgpooling_4/params.txt
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/avgpooling_1/config_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/avgpooling_1/input_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/avgpooling_1/output_ref_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/avgpooling_1/test_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/avgpooling_2/config_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/avgpooling_2/input_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/avgpooling_2/output_ref_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/avgpooling_2/test_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/avgpooling_3/config_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/avgpooling_3/input_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/avgpooling_3/output_ref_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/avgpooling_3/test_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/avgpooling_4/config_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/avgpooling_4/input_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/avgpooling_4/output_ref_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/avgpooling_4/test_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/test_arm_avgpool_s8/Unity/unity_test_arm_avgpool_s8.c
  CMSIS/NN/Tests/UnitTest/TestCases/test_arm_avgpool_s8/test_arm_avgpool_s8.c
  CMSIS/NN/Tests/UnitTest/generate_test_data.py
Labels: NN, review
