Repository ARM-software/CMSIS_5, pull requests merged in 2021-04, with the labels that each got.

#1175 CMSIS-Core(M): Fix cache maintenance functions.
  CMSIS/Core/Include/cachel1_armv7.h
Labels: CORE, bug

#1176 CMSIS-NN : MVE support for SVDF
  ARM.CMSIS.pdsc
  CMSIS/DoxyGen/NN/src/history.txt
  CMSIS/NN/Include/arm_nnsupportfunctions.h
  CMSIS/NN/Source/CMakeLists.txt
  CMSIS/NN/Source/NNSupportFunctions/arm_nn_vec_mat_mult_t_svdf_s8.c
  CMSIS/NN/Source/SVDFunctions/arm_svdf_s8.c
Labels: NN, review

#1178 CoreValidation: Fix Cortex-A builds.
  CMSIS/CoreValidation/Tests/ac5.rtebuild
  CMSIS/CoreValidation/Tests/build.py
  CMSIS/CoreValidation/Tests/config/core_a/rtebuild.sct
  CMSIS/CoreValidation/Tests/main.c
Labels: CORE, bug

#1180 CMSIS-NN : Update history in pdsc file
  ARM.CMSIS.pdsc
Labels: NN

#1184 CoreValidation: Fix Arm Compiler 6 linker warnings.
  CMSIS/CoreValidation/Tests/config/core_a/rtebuild.sct
Labels: CI, CORE, bug

#1185 Add Jenkinsfile for CI integration.
  Jenkinsfile
Labels: CI

#1186 Jenkinsfile: Add quality gate for Compiler warnings.
  Jenkinsfile
Labels: CI
