Repository ARM-software/CMSIS_5, pull requests merged in 2021-05, with the labels that each got.

#1173 [CMSIS Core] Added CM55 Power Mode Control Registers definition
  CMSIS/Core/Include/core_cm55.h
Labels: CI, CORE, enhancement

#1190 Docker: Add dockerfile for Linux build environment.
  .gitignore
  Jenkinsfile
  docker/dockerfile
  docker/getDependencies.sh
  docker/requirements.txt
  docker/rtebuild/armcc.rtebuild
  docker/rtebuild/armclang.rtebuild
  docker/rtebuild/armclang_ltm.rtebuild
  docker/rtebuild/gcc.rtebuild
  docker/rtebuild/toolchain.rtebuild
Labels: CI

#1191 Record compiler warnings for AC6 and GCC.
  Jenkinsfile
Labels: CI

#1193 [CMSIS Core] Set PDEPU low-power state to ON, Clock OFF to favor FP/M…
  Device/ARM/ARMCM55/Source/system_ARMCM55.c
Labels: CORE, review

#1195 Jenkins: Add Cortex-M55 to list of devices.
  Jenkinsfile
Labels: CI, CORE

#1196 CMSIS-NN: ARMC6 Performance improvement for FC kernel
  CMSIS/NN/Source/NNSupportFunctions/arm_nn_vec_mat_mult_t_s8.c
Labels: NN, review

#1197 DSP: Removing deprecated library variant.
  ARM.CMSIS.pdsc
Labels: DSP, review

#1194 CMSIS-Core: aligned __disable_irq, __disable_fault_irq between suppor…
  CMSIS/Core/Include/cmsis_armclang.h
  CMSIS/Core/Include/cmsis_armclang_ltm.h
  CMSIS/CoreValidation/Include/cmsis_cv.h
  CMSIS/CoreValidation/Source/CV_CoreAFunc.c
  CMSIS/CoreValidation/Source/CV_CoreFunc.c
  CMSIS/CoreValidation/Source/ConfigA/CV_Config.h
  CMSIS/CoreValidation/Source/cmsis_cv.c
  CMSIS/CoreValidation/Tests/config/core_a/CV_Config.h
  CMSIS/Core_A/Include/cmsis_armcc.h
  CMSIS/Core_A/Include/cmsis_armclang.h
  CMSIS/Core_A/Include/cmsis_gcc.h
Labels: CI, CORE

#1198 New pack gen bash script.
  .gitignore
  ARM.CMSIS.pdsc
  CMSIS/DoxyGen/Build/src/General.txt
  CMSIS/RTOS/RTX/LIB/fetch_libs.sh
  CMSIS/RTOS2/RTX/Library/fetch_libs.sh
  CMSIS/Utilities/gen_pack.bat
  CMSIS/Utilities/gen_pack.sh
  Jenkinsfile
  README.md
  manifest
Labels: CI, review
