Repository ARM-software/CMSIS_5, pull requests merged in 2021-03, with the labels that each got.

#1136 RTX5: Add os initialization for IAR
  CMSIS/RTOS2/RTX/Source/rtx_lib.c
Labels: RTOS

#1143 CMSIS-DSP: Ensure correlation array index is signed.
  CMSIS/DSP/Source/FilteringFunctions/arm_correlate_f16.c
  CMSIS/DSP/Source/FilteringFunctions/arm_correlate_f32.c
  CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q15.c
  CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q31.c
  CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q7.c
Labels: DSP, review

#1137 CMSIS-NN: Fix static code issues
  CMSIS/NN/.gitignore
  CMSIS/NN/Source/ActivationFunctions/CMakeLists.txt
  CMSIS/NN/Source/BasicMathFunctions/arm_elementwise_add_s8.c
  CMSIS/NN/Source/ConvolutionFunctions/CMakeLists.txt
  CMSIS/NN/Source/FullyConnectedFunctions/CMakeLists.txt
  CMSIS/NN/Source/NNSupportFunctions/CMakeLists.txt
  CMSIS/NN/Source/PoolingFunctions/CMakeLists.txt
  CMSIS/NN/Source/PoolingFunctions/arm_avgpool_s8.c
  CMSIS/NN/Source/SoftmaxFunctions/CMakeLists.txt
  CMSIS/NN/Source/SoftmaxFunctions/arm_softmax_s8.c
  CMSIS/NN/Tests/UnitTest/CMakeLists.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/softmax/input.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/softmax/params.txt
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/softmax/config_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/softmax/input_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/softmax/output_ref_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/softmax/test_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/test_arm_softmax_s8/CMakeLists.txt
  CMSIS/NN/Tests/UnitTest/TestCases/test_arm_softmax_s8/Unity/unity_test_arm_softmax_s8.c
  CMSIS/NN/Tests/UnitTest/TestCases/test_arm_softmax_s8/test_arm_softmax_s8.c
  CMSIS/NN/Tests/UnitTest/generate_test_data.py
  CMSIS/NN/Tests/UnitTest/unittest_targets.py
Labels: NN, review

#1152 CMSIS-NN: Update requirements.txt for unit tests
  CMSIS/NN/Tests/UnitTest/requirements.txt
  CMSIS/NN/Tests/UnitTest/unittest_targets.py
Labels: NN, review

#1153 CMSIS-NN: Update FC test cases to use zero weight offset
  CMSIS/NN/Tests/UnitTest/PregeneratedData/basic/bias.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/basic/input.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/basic/kernel.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/fully_connected/bias.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/fully_connected/input.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/fully_connected/kernel.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/fully_connected_mve_0/bias.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/fully_connected_mve_0/input.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/fully_connected_mve_0/kernel.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/fully_connected_mve_1/bias.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/fully_connected_mve_1/input.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/fully_connected_mve_1/kernel.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/fully_connected_null_bias_0/input.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/fully_connected_null_bias_0/kernel.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/fully_connected_out_activation/bias.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/fully_connected_out_activation/input.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/fully_connected_out_activation/kernel.txt
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/basic/biases_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/basic/input_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/basic/output_ref_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/basic/weights_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/fully_connected/biases_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/fully_connected/config_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/fully_connected/input_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/fully_connected/output_ref_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/fully_connected/weights_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/fully_connected_mve_0/biases_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/fully_connected_mve_0/config_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/fully_connected_mve_0/input_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/fully_connected_mve_0/output_ref_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/fully_connected_mve_0/weights_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/fully_connected_mve_1/biases_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/fully_connected_mve_1/config_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/fully_connected_mve_1/input_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/fully_connected_mve_1/output_ref_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/fully_connected_mve_1/weights_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/fully_connected_null_bias_0/config_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/fully_connected_null_bias_0/input_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/fully_connected_null_bias_0/output_ref_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/fully_connected_null_bias_0/weights_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/fully_connected_out_activation/biases_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/fully_connected_out_activation/config_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/fully_connected_out_activation/input_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/fully_connected_out_activation/output_ref_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/fully_connected_out_activation/weights_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/test_arm_fully_connected_s8/test_arm_fully_connected_s8.c
  CMSIS/NN/Tests/UnitTest/generate_test_data.py
Labels: NN, review

#1161 CMSIS-NN : Update weight offset as zero in FC
  ARM.CMSIS.pdsc
  CMSIS/DoxyGen/NN/src/history.txt
  CMSIS/NN/Include/arm_nn_types.h
  CMSIS/NN/Include/arm_nnfunctions.h
  CMSIS/NN/Include/arm_nnsupportfunctions.h
  CMSIS/NN/Source/FullyConnectedFunctions/arm_fully_connected_s8.c
  CMSIS/NN/Source/NNSupportFunctions/arm_nn_vec_mat_mult_t_s8.c
Labels: NN, review
