Repository ARM-software/CMSIS_5, pull requests merged in 2022-02, with the labels that each got.

#1410 CMSIS-NN: Fix Doxygen warnings
  CMSIS/NN/Include/arm_nnsupportfunctions.h
  CMSIS/NN/Source/PoolingFunctions/arm_avgpool_s16.c
Labels: review, NN

#1376 Core(M): Describe scatter file templates.
  CMSIS/DoxyGen/Core/src/Template.txt
Labels: documentation, review, CORE

#1417 CMSIS-NN: Refactor, remove unused function arm_nn_mat_mult_kernel_s8_s16_reordered
  ARM.CMSIS.pdsc
  CMSIS/NN/Include/arm_nnfunctions.h
  CMSIS/NN/Include/arm_nnsupportfunctions.h
  CMSIS/NN/Source/ConvolutionFunctions/arm_nn_mat_mult_kernel_s8_s16_reordered.c
Labels: review, NN

#1420 CMSIS-NN: Update unit test readme
  CMSIS/NN/Tests/UnitTest/README.md
  CMSIS/NN/Tests/UnitTest/requirements.txt
Labels: NN

#1419 CMSIS-NN: Add elementwise add/mul int16 and unit tests
  ARM.CMSIS.pdsc
  CMSIS/NN/Include/arm_nnfunctions.h
  CMSIS/NN/README.md
  CMSIS/NN/Source/BasicMathFunctions/arm_elementwise_add_s16.c
  CMSIS/NN/Source/BasicMathFunctions/arm_elementwise_add_s8.c
  CMSIS/NN/Source/BasicMathFunctions/arm_elementwise_mul_s16.c
  CMSIS/NN/Source/BasicMathFunctions/arm_elementwise_mul_s8.c
  CMSIS/NN/Tests/UnitTest/CMakeLists.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/add/input.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/add/kernel.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/add_s16/input.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/add_s16/kernel.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/mul/input.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/mul/kernel.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/mul_s16/input.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/mul_s16/kernel.txt
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/add/config_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/add/input1_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/add/input2_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/add/input_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/add/output_ref_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/add/test_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/add_s16/config_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/add_s16/input1_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/add_s16/input2_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/add_s16/output_ref_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/add_s16/test_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/mul/config_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/mul/input1_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/mul/input2_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/mul/output_ref_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/mul/test_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/mul_s16/config_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/mul_s16/input1_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/mul_s16/input2_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/mul_s16/output_ref_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/mul_s16/test_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/test_arm_elementwise_add_s16/CMakeLists.txt
  CMSIS/NN/Tests/UnitTest/TestCases/test_arm_elementwise_add_s16/Unity/unity_test_arm_elementwise_add_s16.c
  CMSIS/NN/Tests/UnitTest/TestCases/test_arm_elementwise_add_s16/test_arm_elementwise_add_s16.c
  CMSIS/NN/Tests/UnitTest/TestCases/test_arm_elementwise_add_s8/CMakeLists.txt
  CMSIS/NN/Tests/UnitTest/TestCases/test_arm_elementwise_add_s8/Unity/unity_test_arm_elementwise_add_s8.c
  CMSIS/NN/Tests/UnitTest/TestCases/test_arm_elementwise_add_s8/test_arm_elementwise_add_s8.c
  CMSIS/NN/Tests/UnitTest/TestCases/test_arm_elementwise_mul_s16/CMakeLists.txt
  CMSIS/NN/Tests/UnitTest/TestCases/test_arm_elementwise_mul_s16/Unity/unity_test_arm_elementwise_mul_s16.c
  CMSIS/NN/Tests/UnitTest/TestCases/test_arm_elementwise_mul_s16/test_arm_elementwise_mul_s16.c
  CMSIS/NN/Tests/UnitTest/TestCases/test_arm_elementwise_mul_s8/CMakeLists.txt
  CMSIS/NN/Tests/UnitTest/TestCases/test_arm_elementwise_mul_s8/Unity/unity_test_arm_elementwise_mul_s8.c
  CMSIS/NN/Tests/UnitTest/TestCases/test_arm_elementwise_mul_s8/test_arm_elementwise_mul_s8.c
  CMSIS/NN/Tests/UnitTest/generate_test_data.py
Labels: NN

#1409 Enhance component conditions for Dcore="Star-MC1".
  .github/workflows/fileheader.sh
  .github/workflows/fileheader.yml
  ARM.CMSIS.pdsc
  CMSIS/Core/Include/cmsis_version.h
  CMSIS/DoxyGen/Core/core.dxy
  CMSIS/DoxyGen/Core/core_CM0-7.dxy
  CMSIS/DoxyGen/Core/src/Overview.txt
  CMSIS/Utilities/PACK.xsd
  CMSIS/Utilities/check_header.sh
  CMSIS/Utilities/gen_pack.sh
Labels: review, CORE, CI
