Repository ARM-software/CMSIS_5, pull requests merged in 2022-06, with the labels that each got.

#1509 CMSIS-NN: Add MVEI support for int16 max pooling
  ARM.CMSIS.pdsc
  CMSIS/DoxyGen/NN/src/history.txt
  CMSIS/NN/README.md
  CMSIS/NN/Source/PoolingFunctions/arm_max_pool_s16.c
Labels: NN

#1510 Rightsizing docker resources
  Jenkinsfile
Labels: CI

#1426 Fix the endless loop issue with GCC O0.
  CMSIS/Core/Include/cachel1_armv7.h
Labels: review, CORE, CI

#1512 CMSIS-NN: Add batch support for 1xN conv
  CMSIS/NN/README.md
  CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_1_x_n_s8.c
  CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_wrapper_s8.c
  CMSIS/NN/Tests/UnitTest/PregeneratedData/conv_1_x_n_1/bias.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/conv_1_x_n_1/input.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/conv_1_x_n_1/kernel.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/conv_1_x_n_2/bias.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/conv_1_x_n_2/input.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/conv_1_x_n_2/kernel.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/conv_1_x_n_3/bias.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/conv_1_x_n_3/input.txt
  CMSIS/NN/Tests/UnitTest/PregeneratedData/conv_1_x_n_3/kernel.txt
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/conv_1_x_n_1/biases_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/conv_1_x_n_1/config_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/conv_1_x_n_1/input_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/conv_1_x_n_1/output_mult_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/conv_1_x_n_1/output_ref_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/conv_1_x_n_1/output_shift_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/conv_1_x_n_1/test_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/conv_1_x_n_1/weights_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/conv_1_x_n_2/biases_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/conv_1_x_n_2/config_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/conv_1_x_n_2/input_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/conv_1_x_n_2/output_mult_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/conv_1_x_n_2/output_ref_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/conv_1_x_n_2/output_shift_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/conv_1_x_n_2/test_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/conv_1_x_n_2/weights_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/conv_1_x_n_3/biases_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/conv_1_x_n_3/config_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/conv_1_x_n_3/input_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/conv_1_x_n_3/output_mult_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/conv_1_x_n_3/output_ref_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/conv_1_x_n_3/output_shift_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/conv_1_x_n_3/test_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/TestData/conv_1_x_n_3/weights_data.h
  CMSIS/NN/Tests/UnitTest/TestCases/test_arm_convolve_s8/test_arm_convolve_s8.c
  CMSIS/NN/Tests/UnitTest/generate_test_data.py
Labels: NN
